#!/bin/python3

import sys

n,k = input().strip().split(' ')
n = int(n)
k = int(k)
arr = [int(arr_temp) for arr_temp in input().strip().split(' ')]

pg = 0
special = 0

for i in arr:
    
    if(i >= k):
           
        start_pg = pg + 1
        curr_pg = start_pg
        bonus = int(i / k) + (i % k > 0) # add on appropriate number of pages
        pg += bonus
        end_pg = pg
        
        for i in range(1,(end_pg-start_pg+2)):
            if(i != 1):
                m = (i-1)*k+1
                for h in range (m,m+k):
                    if(h==curr_pg):
                        special += 1
                        break
            else:
                for h in range(1,k+1):
                    if(h==curr_pg):
                        special += 1
                        break
            curr_pg += 1
                
        
        
    else:
        pg += 1
        
        # Account for the case of a single page
        if(i>=pg):
            special +=1 
        
print(special)
